# Generated by Django 4.2.1 on 2023-05-06 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split_wise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpenseowedby',
            old_name='user_expense',
            new_name='user_expense_owed',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL),
        ),
    ]
