# Generated by Django 4.2.1 on 2023-05-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_wise', '0003_expense_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='participants',
            new_name='members',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'created_by')},
        ),
    ]
