# Generated by Django 4.2.1 on 2023-05-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_wise', '0007_alter_expense_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('name', 'created_by')},
        ),
    ]
