# Generated by Django 4.1.5 on 2023-01-07 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
                ('spot_status', models.CharField(choices=[('AVL', 'Available'), ('OCU', 'Occupied'), ('OOO', 'OutOfOrder')], default='AVL', max_length=3)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkingfloor')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('registration', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DON', 'Done'), ('PEN', 'Pending')], default='PEN', max_length=3)),
                ('floor_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkingfloor')),
                ('spot_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkingspot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='parkingfloor',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot'),
        ),
        migrations.CreateModel(
            name='ExitGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ManyToManyField(to='parking_lot.operator')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkinglot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.entrygate')),
            ],
        ),
    ]
