# Generated by Django 4.1.5 on 2023-01-09 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.DurationField()),
                ('languages', models.ManyToManyField(to='book_my_show.language')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTicket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mode', models.CharField(choices=[('NET', 'Net Banking'), ('DBT', 'Debit Card'), ('CRD', 'Credit Card'), ('UPI', 'Unified Payment Interface')], default='UPI', max_length=3)),
                ('status', models.CharField(choices=[('SUC', 'Success'), ('FAL', 'Failure')], default='SUC', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRG', 'In Progress'), ('SUC', 'Success'), ('FAL', 'Failure')], default='PRG', max_length=3)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_my_show.payment')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_my_show.movieticket')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.city')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.screen')),
                ('theatre', models.ForeignKey(default='PVR Cinemas', on_delete=django.db.models.deletion.CASCADE, to='book_my_show.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=1)),
                ('column', models.IntegerField()),
                ('type', models.CharField(choices=[('RYL', 'Royale'), ('CLB', 'Club'), ('EXC', 'Executive')], default='EXC', max_length=3)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.screen')),
                ('theatre', models.ForeignKey(default='PVR Cinemas', on_delete=django.db.models.deletion.CASCADE, to='book_my_show.theatre')),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.theatre'),
        ),
        migrations.AddField(
            model_name='movieticket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.user'),
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book_my_show.seat')),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('BOK', 'Booked')], default='AVL', max_length=3)),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.show')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.movieticket')),
            ],
        ),
    ]
