# Generated by Django 4.1.5 on 2023-01-09 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='screen',
            name='theatre',
        ),
        migrations.AlterField(
            model_name='showseat',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_show.transaction'),
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ManyToManyField(to='book_my_show.theatre'),
        ),
    ]
