# Generated by Django 4.1.5 on 2023-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0002_remove_transaction_id_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='theatre',
        ),
        migrations.AddField(
            model_name='seat',
            name='theatre',
            field=models.ManyToManyField(to='book_my_show.theatre'),
        ),
    ]
