# Generated by Django 4.1.5 on 2023-01-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0003_remove_seat_theatre_seat_theatre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ManyToManyField(to='book_my_show.screen'),
        ),
    ]
