# Generated by Django 4.1.5 on 2023-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0005_alter_show_start_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('movie', 'start_time', 'language', 'screen', 'theatre'), name='constraint_name'),
        ),
    ]
