# Generated by Django 4.1.5 on 2023-01-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0006_show_constraint_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='show',
            name='constraint_name',
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('movie', 'start_time', 'language', 'screen', 'theatre'), name='unique_show'),
        ),
    ]
