# Generated by Django 4.1.5 on 2023-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0008_visual_remove_movie_duration_alter_movie_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='visual',
            field=models.ManyToManyField(to='book_my_show.visual'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(to='book_my_show.language'),
        ),
    ]
