# Generated by Django 4.1.5 on 2023-01-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_show', '0009_movie_visual_alter_movie_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='visuals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_my_show.visual'),
            preserve_default=False,
        ),
    ]
